config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resources :menus, only: [:new, :create, :show, :index] do
  	resources :items, only: [:new, :create]
  end
  get '/sessions/new', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/sessions', to: 'sessions#destroy', as: 'logout'
  root 'menus#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :menu

	validates :title, :description, :price, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
	has_many :items
	belongs_to :user
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
	belongs_to :menu

	validates :title, :description, :price, presence: true
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
	include BCrypt

	has_many :menus

	validates :username, :password_hash, presence: true
	validates :username, uniqueness: true

	def password
		@password ||= Password.new(password_hash)
	end

	def password=(new_password)
		@password = Password.create(new_password)
		self.password_hash = @password
	end	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
  	redirect_to '/' unless current_user
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def new
		authorize
		@item = Item.new
		@menu = Menu.find_by(id: params[:menu_id])
	end

	def create
		authorize
		@item = Item.new(item_params)
		@menu = Menu.find_by(id: params[:menu_id])
		@item.menu = @menu
		if @item.save
			redirect_to menu_path(@menu)
		else
			render 'new'
		end
	end

	private
	def item_params
		params.require(:item).permit(:title, :description, :price, :menu_id)
	end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

	def new
		authorize
		@menu = Menu.new
	end

	def create
		authorize
		@menu = Menu.new(menu_params)
		@menu.user = current_user
		if @menu.save
			render 'show'
		else
			render 'new'
		end
	end

	def index
		@menus = Menu.all
	end

	def show
		@menu = Menu.find(params[:id])
	end

	private
	def menu_params
		params.require(:menu).permit(:name)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_username(params[:username])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to '/'
		else
			@errors = ['Invalid username or password.']
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		user = User.new(user_params)
		if user.save
			session[:user_id] = user.id
			redirect_to '/'
		else
			@errors = user.errors.full_messages
			@user = User.new
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:username, :password_hash)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/new.html.erb
<% if @item.errors.any? %>
	<ul>
		<%= @item.errors.full_messages.each do |message| %>
		<% end %>
	</ul> 
<% end %>
<%= form_for @item, url: menu_items_path do |f| %>
	<% f.hidden_field :menu_id, :value => @menu.id %>
	<%= f.label :title %>
	<%= f.text_field :title %><br>

	<%=f.label :description %>
	<%= f.text_field :description %><br>

	<%=f.label :price %>
	<%=f.number_field :price, step: :any %>

	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMenu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<h1 id="title">MyMenu</h1>
  	<div id='nav'>
  		<nav> <%= link_to 'Home', root_path %> |
  			<% if current_user %>
  				<%= link_to 'Logout', logout_path %> | <%= link_to 'New Menu', new_menu_path %> | <span id='user-info'><%= current_user.username %> </span>
  			<% else %>
  				<%= link_to 'Register', new_user_path %> |  <%= link_to 'Login', sessions_new_path, id: 'login-link'  %>
  			<% end %>
  		</nav>
      <div id="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/menus/index.html.erb
<h1>Menus</h1>
<h2>Here's the menus others have created so far:</h2>
<% if !@menus.empty? %>
<ol>
		<% @menus.each do |menu| %>
		<strong><li><%= link_to menu.name, menu_path(menu) %></li></strong>
		<% end %>
</ol>
<% else %>
	<h3>No one has created any menus! Click <%= link_to 'here', new_menu_path %> to make one now!</h3>
<% end %>

app/views/menus/new.html.erb
<% if @menu.errors.any? %>
	<ul>
		<%= @menu.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

<h2>Give your menu a name!</h2>

<%= form_for @menu do |f| %>
	<%=f.text_field :name %>
	<%=f.submit "Create New Menu" %>
<% end %>

app/views/menus/show.html.erb
<h1><%= @menu.name %></h1>
<h2>Created by: <%= @menu.user.username %></h2>
<% if @menu.items.empty? %>
	<h4>Your menu doesn't have any items in it yet! click <%= link_to 'here', new_menu_item_path(@menu) %> to add some!</h4>
<% else %> 
	<%= @menu.items.each do |item| %>
		<h3><%= item.title %></h3>
		<h4>$<%= item.price %></h4>
		<p><%= item.description %></p>
	<% end %>
	<%= link_to 'Add more items!', new_menu_item_path(@menu) %>
<% end %>

app/views/users/new.html.erb
<%= render 'sessions/errors' %>

<h2> Register </h2>

<%= form_for @user, url: { action: "create"} do |f| %>
	<%= f.label :username %>
	<%= f.text_field :username %>
	<%= f.label :password %>
	<%= f.password_field :password_hash %>
	<%= f.submit "Register" %>
<% end %>